/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Pessoa;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicos.ServicosFactory;
import servicos.VitimaServicos;

/**
 *
 * @author 182310085
 */
public class JFvitima extends javax.swing.JFrame {

    int idEdit;

    /**
     * Creates new form JFvitima
     */
    public JFvitima() {
        initComponents();
        addRowToTable();
        jbeditarvitima.setVisible(false);
        jbdeletarvitima.setVisible(false);

    }

    public void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jtVitimas.getModel();
        model.getDataVector().removeAllElements();//remove todas as linhas
        model.fireTableDataChanged();
        //cria vetor de 5 posições que corresponde as colunas da tabela
        Object rowData[] = new Object[5];
        VitimaServicos vitimasS = ServicosFactory.getVitimaServicos();
        //percorer lista e popula vetor e add vetor e tabela
        for (Pessoa vitima : vitimasS.listaVitimas()) {
            rowData[0] = vitima.getId();
            rowData[1] = vitima.getNome();
            rowData[2] = vitima.getOlho();
            //if ternary operator
            rowData[3] = vitima.isSexo() == false ? "Feminino" : "Masculino";
            rowData[4] = vitima.getPontosDeVida();
            model.addRow(rowData);

        }
    }//fim addrowToTable

    private void limpaCampos() {
        jtfnomevitima.setText("");
        jtfcabelovitima.setText("");
        jtfolhovitima.setText("");
        jtfpelevitima.setText("");
        bgSexoVitima.clearSelection();
        jtfnomevitima.requestFocus();

    }

    private boolean validainputs() {
        if (jtfnomevitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "precnher nome");
            jtfnomevitima.requestFocus();
            return false;
        }

        if (jtfolhovitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "precnher olho");
            jtfolhovitima.requestFocus();
            return false;
        }

        if (jtfcabelovitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "precnher cabelo");
            jtfcabelovitima.requestFocus();
            return false;
        }

        if (jtfpelevitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "precnher pele");
            jtfpelevitima.requestFocus();
            return false;
        }

        if (!jrbFemininoVitima.isSelected() && !jrbMasculinoVitima.isSelected()) {
            JOptionPane.showMessageDialog(this, "selecionar sexo");
            return false;

        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoVitima = new javax.swing.ButtonGroup();
        jtfCabeloVitima = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfnomevitima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfcabelovitima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfolhovitima = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfpelevitima = new javax.swing.JTextField();
        jrbFemininoVitima = new javax.swing.JRadioButton();
        jrbMasculinoVitima = new javax.swing.JRadioButton();
        jLSexoVitima = new javax.swing.JLabel();
        jbSalvarVitima = new javax.swing.JButton();
        jbLimparvitima = new javax.swing.JButton();
        jbdeletarvitima = new javax.swing.JButton();
        jbeditarvitima = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVitimas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Vitima");

        jLabel2.setText("Nome:");

        jtfnomevitima.setName("jtfNome Vitima"); // NOI18N
        jtfnomevitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnomevitimaActionPerformed(evt);
            }
        });

        jLabel3.setText("Cabelo:");

        jtfcabelovitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcabelovitimaActionPerformed(evt);
            }
        });

        jLabel4.setText("Olho:");

        jLabel5.setText("Pele:");

        bgSexoVitima.add(jrbFemininoVitima);
        jrbFemininoVitima.setText("Feminino");

        bgSexoVitima.add(jrbMasculinoVitima);
        jrbMasculinoVitima.setText("Maculino");
        jrbMasculinoVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMasculinoVitimaActionPerformed(evt);
            }
        });

        jLSexoVitima.setText("Sexo:");

        jbSalvarVitima.setText("Salvar");
        jbSalvarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarVitimaActionPerformed(evt);
            }
        });

        jbLimparvitima.setText("Limpar");
        jbLimparvitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparvitimaActionPerformed(evt);
            }
        });

        jbdeletarvitima.setText("Deletar");
        jbdeletarvitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeletarvitimaActionPerformed(evt);
            }
        });

        jbeditarvitima.setText("Editar");
        jbeditarvitima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbeditarvitimaMouseClicked(evt);
            }
        });
        jbeditarvitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditarvitimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtfCabeloVitimaLayout = new javax.swing.GroupLayout(jtfCabeloVitima);
        jtfCabeloVitima.setLayout(jtfCabeloVitimaLayout);
        jtfCabeloVitimaLayout.setHorizontalGroup(
            jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jtfCabeloVitimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtfCabeloVitimaLayout.createSequentialGroup()
                        .addComponent(jbSalvarVitima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbLimparvitima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbdeletarvitima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbeditarvitima))
                    .addGroup(jtfCabeloVitimaLayout.createSequentialGroup()
                        .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfnomevitima, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jtfCabeloVitimaLayout.createSequentialGroup()
                                .addComponent(jtfcabelovitima, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfolhovitima))
                            .addGroup(jtfCabeloVitimaLayout.createSequentialGroup()
                                .addComponent(jtfpelevitima, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLSexoVitima)
                                .addGap(24, 24, 24)
                                .addComponent(jrbFemininoVitima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbMasculinoVitima)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jtfCabeloVitimaLayout.setVerticalGroup(
            jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtfCabeloVitimaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfnomevitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfcabelovitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtfolhovitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfpelevitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbFemininoVitima)
                    .addComponent(jrbMasculinoVitima)
                    .addComponent(jLSexoVitima))
                .addGap(18, 18, 18)
                .addGroup(jtfCabeloVitimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarVitima)
                    .addComponent(jbLimparvitima)
                    .addComponent(jbdeletarvitima)
                    .addComponent(jbeditarvitima))
                .addGap(0, 108, Short.MAX_VALUE))
        );

        jtVitimas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Olho", "Sexo", "HP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVitimas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVitimasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtVitimas);
        if (jtVitimas.getColumnModel().getColumnCount() > 0) {
            jtVitimas.getColumnModel().getColumn(0).setResizable(false);
            jtVitimas.getColumnModel().getColumn(1).setResizable(false);
            jtVitimas.getColumnModel().getColumn(2).setResizable(false);
            jtVitimas.getColumnModel().getColumn(3).setResizable(false);
            jtVitimas.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfCabeloVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfCabeloVitima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfnomevitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnomevitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnomevitimaActionPerformed

    private void jtfcabelovitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcabelovitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfcabelovitimaActionPerformed

    private void jrbMasculinoVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMasculinoVitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMasculinoVitimaActionPerformed

    private void jbLimparvitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparvitimaActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparvitimaActionPerformed

    private void jbSalvarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarVitimaActionPerformed
        if (jbSalvarVitima.getText().equals("salvar")) {

            if (validainputs()) {
                Pessoa v = new Pessoa();
                v.setNome(jtfnomevitima.getText().toUpperCase());
                v.setOlho(jtfolhovitima.getText().toUpperCase());
                v.setCabelo(jtfcabelovitima.getText().toUpperCase());
                v.setPele(jtfpelevitima.getText().toUpperCase());
                if (jrbFemininoVitima.isSelected() || jrbMasculinoVitima.isSelected()) {
                    v.setSexo(!jrbFemininoVitima.isSelected());
                }
                VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
                vitimaS.cadastrarvitima(v);
                addRowToTable();
                limpaCampos();

            }//fim do salvar
        } else {
            //codigo update
            Pessoa vit = new Pessoa();
            vit.setId(idEdit);
            vit.setNome(jtfnomevitima.getText());
            vit.setCabelo(jtfcabelovitima.getText());
            vit.setOlho(jtfolhovitima.getText());
            vit.setPele(jtfpelevitima.getText());
            VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
            vitimaS.atualizarVitima(vit);
            addRowToTable();
            JOptionPane.showMessageDialog(this, "vitima atualizada com sucesso! ");
            jbDefault();
            

        }//fim do update
        
    }//GEN-LAST:event_jbSalvarVitimaActionPerformed

    private void jbDefault(){
        
        jbSalvarVitima.setText("salvar");
            jLSexoVitima.setEnabled(true);
            jrbFemininoVitima.setEnabled(true);
            jrbMasculinoVitima.setEnabled(true);
            jbLimparvitima.setVisible(true);
            jbdeletarvitima.setVisible(false);
            jbdeletarvitima.setText("Deletar");
            jbdeletarvitima.setVisible(false);
    }
    
    private void jbdeletarvitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeletarvitimaActionPerformed

        if(jbdeletarvitima.getText().equals("Deletar")){
        int linha = jtVitimas.getSelectedRow();
        int id = (int) jtVitimas.getValueAt(linha, 0);
        String nome = (String) jtVitimas.getValueAt(linha, 1);
        Object[] btnMSG = {"Sim", "Não"};
        int resp = JOptionPane.showOptionDialog(this, "Deseja mesmo deletar?" + nome, ".:Deletar:.", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, btnMSG, btnMSG);
        if (resp == 0) {
            VitimaServicos vitimasS = ServicosFactory.getVitimaServicos();
            vitimasS.deletarVitima(id);
            JOptionPane.showMessageDialog(this, "Vitima " + nome + " deletada com sucesso ");
        } else {
            JOptionPane.showMessageDialog(this, "Ok, delete cancelado pelo usuario com sucesso");
        }

        }else{
            
            jbDefault();
            limpaCampos();
            
        }
    }//GEN-LAST:event_jbdeletarvitimaActionPerformed

    private void jbeditarvitimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbeditarvitimaMouseClicked

    }//GEN-LAST:event_jbeditarvitimaMouseClicked

    private void jtVitimasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVitimasMouseClicked
        jbeditarvitima.setVisible(true);
        jbdeletarvitima.setVisible(true);
    }//GEN-LAST:event_jtVitimasMouseClicked

    private void jbeditarvitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditarvitimaActionPerformed
        jbLimparvitima.setEnabled(false);
        jbSalvarVitima.setText("Atualizar");
        jrbFemininoVitima.setVisible(false);
        jrbMasculinoVitima.setVisible(false);
        jLSexoVitima.setVisible(false);
        jbdeletarvitima.setText("cancelar");

        // Buscar vitima e carregar nos campos
        int linha = jtVitimas.getSelectedRow();
        idEdit = (int) jtVitimas.getValueAt(linha, 0);
        VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
        Pessoa vitima = vitimaS.getVitimaById(idEdit);
        jtfnomevitima.setText(vitima.getNome());
        jtfcabelovitima.setText(vitima.getCabelo());
        jtfolhovitima.setText(vitima.getOlho());
        jtfpelevitima.setText(vitima.getPele());


    }//GEN-LAST:event_jbeditarvitimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFvitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFvitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFvitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFvitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFvitima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoVitima;
    private javax.swing.JLabel jLSexoVitima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbLimparvitima;
    private javax.swing.JButton jbSalvarVitima;
    private javax.swing.JButton jbdeletarvitima;
    private javax.swing.JButton jbeditarvitima;
    private javax.swing.JRadioButton jrbFemininoVitima;
    private javax.swing.JRadioButton jrbMasculinoVitima;
    private javax.swing.JTable jtVitimas;
    private javax.swing.JPanel jtfCabeloVitima;
    private javax.swing.JTextField jtfcabelovitima;
    private javax.swing.JTextField jtfnomevitima;
    private javax.swing.JTextField jtfolhovitima;
    private javax.swing.JTextField jtfpelevitima;
    // End of variables declaration//GEN-END:variables
}
